# Generated by Django 5.1.15 on 2026-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bespoke', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bespokeattachment',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
    ]
