# Generated by Django 6.1 on 2026-08-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default="Virtuoso's Gems", max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('default_currency', models.CharField(default='USD', max_length=10)),
                ('tax_rate_percentage', models.DecimalField(decimal_places=2, default=8.5, max_digits=5)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=500, max_digits=12)),
                ('order_prefix', models.CharField(default='GEM-', max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'store settings',
                'verbose_name_plural': 'store settings',
            },
        ),
    ]
