# Generated by Django 5.1.15 on 2026-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
