# Generated by Django 5.1.15 on 2026-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(max_length=500),
        ),
    ]
