# Generated by Django 5.1.15 on 2026-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.URLField(max_length=500),
        ),
    ]
