/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Luxe Facet Design System
        primary: '#003527',
        'primary-container': '#064e3b',
        'primary-fixed': '#b0f0d6',
        'primary-fixed-dim': '#95d3ba',
        'on-primary': '#ffffff',
        'on-primary-container': '#80bea6',
        'on-primary-fixed': '#002117',
        'on-primary-fixed-variant': '#0b513d',
        'inverse-primary': '#95d3ba',
        
        secondary: '#006c49',
        'secondary-container': '#6cf8bb',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00714d',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        
        tertiary: '#242f41',
        'tertiary-container': '#3a4558',
        'tertiary-fixed': '#d8e3fb',
        'tertiary-fixed-dim': '#bcc7de',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#a7b2c9',
        'on-tertiary-fixed': '#111c2d',
        'on-tertiary-fixed-variant': '#3c475a',
        
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#404944',
        
        outline: '#707974',
        'outline-variant': '#bfc9c3',
        
        background: '#f7f9fb',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
        
        // Semantic aliases
        success: '#10B981',
        'success-bg': '#ECFDF5',
        'success-text': '#064E3B',
        warning: '#F59E0B',
        'warning-bg': '#FFFBE6',
        'warning-text': '#B45309',
        error: '#ba1a1a',
        'error-bg': '#FEF2F2',
        'error-text': '#991B1B',
        info: '#3B82F6',
        'info-bg': '#EFF6FF',
        'info-text': '#1D4ED8',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'base': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '24px',
        'margin': '24px',
        'max-width': '1440px',
      },
      fontFamily: {
        body: ['Inter', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        display: ['Inter', 'sans-serif'],
        mono: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['28px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-label': ['13px', { lineHeight: '18px', fontWeight: '500' }],
      },
      boxShadow: {
        'resting': '0px 1px 3px rgba(0, 0, 0, 0.05), 0px 1px 2px rgba(0, 0, 0, 0.03)',
        'floating': '0px 10px 15px -3px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
}